/**
 * Generated by "@vuepress/internal-root-mixins"
 */
import m0 from "/Users/yangpeng/Blog/node_modules/_@vuepress_core@1.8.2@@vuepress/core/lib/client/root-mixins/updateMeta.js"
import m1 from "/Users/yangpeng/Blog/node_modules/_@vuepress_plugin-nprogress@1.8.2@@vuepress/plugin-nprogress/clientRootMixin.js"
import m2 from "/Users/yangpeng/Blog/node_modules/_@vuepress_plugin-medium-zoom@1.8.2@@vuepress/plugin-medium-zoom/clientRootMixin.js"

export default [
  m0,
  m1,
  m2
]