/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\Blog\\blog\\node_modules\\@vuepress\\theme-blog\\layouts\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-83582c68",
    path: "/2018/10/27/javascript-async/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-83582c68").then(next)
    },
  },
  {
    path: "/2018/10/27/javascript-async/index.html",
    redirect: "/2018/10/27/javascript-async/"
  },
  {
    path: "/_posts/2018-10-27-javascript-async.html",
    redirect: "/2018/10/27/javascript-async/"
  },
  {
    name: "v-36734306",
    path: "/2019/04/05/javascript-design/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-36734306").then(next)
    },
  },
  {
    path: "/2019/04/05/javascript-design/index.html",
    redirect: "/2019/04/05/javascript-design/"
  },
  {
    path: "/_posts/2019-4-5-javascript-design.html",
    redirect: "/2019/04/05/javascript-design/"
  },
  {
    name: "v-6d376834",
    path: "/2019/05/29/utils-func/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-6d376834").then(next)
    },
  },
  {
    path: "/2019/05/29/utils-func/index.html",
    redirect: "/2019/05/29/utils-func/"
  },
  {
    path: "/_posts/2019-5-29-utils-func.html",
    redirect: "/2019/05/29/utils-func/"
  },
  {
    name: "v-f99b5fb4",
    path: "/2018/09/25/javascript-closure/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-f99b5fb4").then(next)
    },
  },
  {
    path: "/2018/09/25/javascript-closure/index.html",
    redirect: "/2018/09/25/javascript-closure/"
  },
  {
    path: "/_posts/2018-9-25-javascript-closure.html",
    redirect: "/2018/09/25/javascript-closure/"
  },
  {
    name: "v-c8ba5d74",
    path: "/2019/05/28/webpack-init/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-c8ba5d74").then(next)
    },
  },
  {
    path: "/2019/05/28/webpack-init/index.html",
    redirect: "/2019/05/28/webpack-init/"
  },
  {
    path: "/_posts/2019-5-28-webpack-init.html",
    redirect: "/2019/05/28/webpack-init/"
  },
  {
    name: "v-24d375c8",
    path: "/2019/05/28/javascript-prototype/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-24d375c8").then(next)
    },
  },
  {
    path: "/2019/05/28/javascript-prototype/index.html",
    redirect: "/2019/05/28/javascript-prototype/"
  },
  {
    path: "/_posts/2018-9-5-javascript-prototype.html",
    redirect: "/2019/05/28/javascript-prototype/"
  },
  {
    name: "v-cb7bff34",
    path: "/2018/09/06/business-standard/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-cb7bff34").then(next)
    },
  },
  {
    path: "/2018/09/06/business-standard/index.html",
    redirect: "/2018/09/06/business-standard/"
  },
  {
    path: "/_posts/2018-9-6-business-standard.html",
    redirect: "/2018/09/06/business-standard/"
  },
  {
    name: "v-b2754d56",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b2754d56").then(next)
    },
    meta: {"pid":"post","id":"post"}
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-b1564aac",
    path: "/tag/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterKey", "v-b1564aac").then(next)
    },
    meta: {"pid":"tag","id":"tag"}
  },
  {
    path: "/tag/index.html",
    redirect: "/tag/"
  },
  {
    name: "v-5f97b358",
    path: "/tag/Javascript/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterPagination", "v-5f97b358").then(next)
    },
    meta: {"pid":"tag","id":"Javascript"}
  },
  {
    path: "/tag/Javascript/index.html",
    redirect: "/tag/Javascript/"
  },
  {
    name: "v-ae3001b6",
    path: "/tag/设计模式/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterPagination", "v-ae3001b6").then(next)
    },
    meta: {"pid":"tag","id":"设计模式"}
  },
  {
    path: "/tag/设计模式/index.html",
    redirect: "/tag/设计模式/"
  },
  {
    name: "v-ad8a01a8",
    path: "/tag/Webpack/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterPagination", "v-ad8a01a8").then(next)
    },
    meta: {"pid":"tag","id":"Webpack"}
  },
  {
    path: "/tag/Webpack/index.html",
    redirect: "/tag/Webpack/"
  },
  {
    name: "v-97019ce8",
    path: "/tag/工具/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterPagination", "v-97019ce8").then(next)
    },
    meta: {"pid":"tag","id":"工具"}
  },
  {
    path: "/tag/工具/index.html",
    redirect: "/tag/工具/"
  },
  {
    name: "v-038768cf",
    path: "/tag/业务/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterPagination", "v-038768cf").then(next)
    },
    meta: {"pid":"tag","id":"业务"}
  },
  {
    path: "/tag/业务/index.html",
    redirect: "/tag/业务/"
  },
  {
    name: "v-8fdafa70",
    path: "/page/2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8fdafa70").then(next)
    },
    meta: {"pid":"post","id":"post"}
  },
  {
    path: "/page/2/index.html",
    redirect: "/page/2/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]