/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tag": {
    "Javascript": {
      "key": "Javascript",
      "scope": "tag",
      "path": "/tag/Javascript/",
      "pageKeys": [
        "v-00d7eeae",
        "v-48f50183",
        "v-41c1ad79",
        "v-701115ba",
        "v-74e62bc3"
      ]
    },
    "Webpack": {
      "key": "Webpack",
      "scope": "tag",
      "path": "/tag/Webpack/",
      "pageKeys": [
        "v-5b151f3a"
      ]
    },
    "工具": {
      "key": "工具",
      "scope": "tag",
      "path": "/tag/工具/",
      "pageKeys": [
        "v-5b151f3a",
        "v-48f50183"
      ]
    },
    "设计模式": {
      "key": "设计模式",
      "scope": "tag",
      "path": "/tag/设计模式/",
      "pageKeys": [
        "v-701115ba"
      ]
    },
    "业务": {
      "key": "业务",
      "scope": "tag",
      "path": "/tag/业务/",
      "pageKeys": [
        "v-2bc63283"
      ]
    }
  }
}