/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tag": {
    "Javascript": {
      "key": "Javascript",
      "scope": "tag",
      "path": "/tag/Javascript/",
      "pageKeys": [
        "v-83582c68",
        "v-36734306",
        "v-f99b5fb4"
      ]
    },
    "设计模式": {
      "key": "设计模式",
      "scope": "tag",
      "path": "/tag/设计模式/",
      "pageKeys": [
        "v-36734306"
      ]
    },
    "Webpack": {
      "key": "Webpack",
      "scope": "tag",
      "path": "/tag/Webpack/",
      "pageKeys": [
        "v-c8ba5d74",
        "v-24d375c8"
      ]
    },
    "工具": {
      "key": "工具",
      "scope": "tag",
      "path": "/tag/工具/",
      "pageKeys": [
        "v-c8ba5d74",
        "v-24d375c8"
      ]
    },
    "业务": {
      "key": "业务",
      "scope": "tag",
      "path": "/tag/业务/",
      "pageKeys": [
        "v-cb7bff34"
      ]
    }
  }
}