/**
 * Generated by "@vuepress/plugin-blog"
 */

import sorters from './pageSorters'
import filters from './pageFilters'

export default [{
  pid: "post",
  id: "post",
  filter: filters.post,
  sorter: sorters.post,
  pages: [{"path":"/","interval":[0,4]},{"path":"/page/2/","interval":[5,7]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tag",
  id: "Javascript",
  filter: filters.tag,
  sorter: sorters.tag,
  pages: [{"path":"/tag/Javascript/","interval":[0,3]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tag",
  id: "设计模式",
  filter: filters.tag,
  sorter: sorters.tag,
  pages: [{"path":"/tag/设计模式/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tag",
  id: "Webpack",
  filter: filters.tag,
  sorter: sorters.tag,
  pages: [{"path":"/tag/Webpack/","interval":[0,2]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tag",
  id: "工具",
  filter: filters.tag,
  sorter: sorters.tag,
  pages: [{"path":"/tag/工具/","interval":[0,2]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tag",
  id: "业务",
  filter: filters.tag,
  sorter: sorters.tag,
  pages: [{"path":"/tag/业务/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
}]