/**
 * Generated by "vuepress-plugin-mailchimp"
 */

    const { endpoint, submitText, content, title, popupConfig = {} } = {"endpoint":"https://gmail.us5.list-manage.com/subscribe/post?u=942c0d587f8ea28269e80d6cd&amp;id=d77d789d53"}
    
    const {
    enabled: popupEnabled = true,
    component: popupComponent = "Popup",
    timeout: popupTimeout = 3000
    } = popupConfig;
    
    export { endpoint, submitText, content, title, popupEnabled, popupComponent, popupTimeout };